INSERT INTO PAIS VALUES (1, 'Brasil');
INSERT INTO PAIS VALUES (2, 'Venezuela');
INSERT INTO PAIS VALUES (3, 'Angola');
INSERT INTO PAIS VALUES (4, 'Alemanha');
INSERT INTO PAIS VALUES (5, 'Espanha');
COMMIT;
